# Generated by Django 5.0.6 on 2026-04-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('enrollment_date', models.DateField(verbose_name='Дата зачисления')),
                ('health_group', models.CharField(choices=[('I', 'I группа'), ('II', 'II группа'), ('III', 'III группа'), ('IV', 'IV группа'), ('V', 'V группа')], default='I', max_length=5, verbose_name='Группа здоровья')),
                ('medical_notes', models.JSONField(blank=True, default=dict, help_text='Например: {"allergies": ["пыльца"], "chronic": []}', verbose_name='Медицинские сведения')),
                ('status', models.CharField(choices=[('active', 'Посещает'), ('expelled', 'Отчислен'), ('graduated', 'Выпущен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Воспитанник',
                'verbose_name_plural': 'Воспитанники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Электронная почта')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адрес')),
                ('relation', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун'), ('other', 'Иное')], max_length=20, verbose_name='Степень родства')),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='children.child', verbose_name='Дети')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['group'], name='children_ch_group_i_85111d_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['status'], name='children_ch_status_d1a9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['last_name'], name='children_ch_last_na_ee2e2a_idx'),
        ),
    ]
