# Generated by Django 5.0.6 on 2026-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('age_category', models.CharField(choices=[('1-2 года', '1-2 года (ясельная)'), ('2-3 года', '2-3 года (первая младшая)'), ('3-4 года', '3-4 года (вторая младшая)'), ('4-5 лет', '4-5 лет (средняя)'), ('5-6 лет', '5-6 лет (старшая)'), ('6-7 лет', '6-7 лет (подготовительная)')], max_length=50, verbose_name='Возрастная категория')),
                ('direction', models.CharField(choices=[('общеразвивающая', 'Общеразвивающая'), ('компенсирующая', 'Компенсирующая'), ('комбинированная', 'Комбинированная')], default='общеразвивающая', max_length=50, verbose_name='Направленность')),
                ('max_capacity', models.PositiveSmallIntegerField(default=25, verbose_name='Максимальная наполняемость')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
    ]
