# Generated by Django 5.0.6 on 2026-04-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('absence_reason', models.CharField(blank=True, choices=[('illness', 'Болезнь'), ('family', 'Семейные обстоятельства'), ('vacation', 'Отпуск родителей'), ('other', 'Иное')], default='', max_length=20, verbose_name='Причина отсутствия')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='children.child', verbose_name='Воспитанник')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'ordering': ['-date', 'child__last_name'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_337b1d_idx'), models.Index(fields=['child', 'date'], name='attendance__child_i_40b74e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('child', 'date'), name='unique_child_date'),
        ),
    ]
